name: build
on:
  push: 
    branches: [master]
    path-ignores:
      - "**.md"

  pull_request: 
    branches: [master]
    path-ignores:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable]
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v0.1
        with:
          sdk: ${{ matrix.sdk }}

          
      - uses: stelynx/dart-full-coverage@v1.0.3
        with:
          package: egakcap
          ignore: "*_state.dart, do_not_import_me.dart"

      - name: install dependencies
        run: dart pub get
      
      - name: run test coverage
        run: nohup pub run test_coverage &

      - name: build test
        run: dart --no-sound-null-safety test --platform vm

      - name: codecov test
        uses: codecov/codecov-action@v1
        with: 
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CODECOV_TOKEN }} 
          verbose: true 
      
