name: build
on:
  push: 
    branches: [master]
    path-ignores:
      - "**.md"

  pull_request: 
    branches: [master]
    path-ignores:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [2.1.x, 2.2.x, 2.3.x, 2.4.x, stable]
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: "stable"
          
      - uses: stelynx/dart-full-coverage@v1.0.3
        with:
          package: egakcap
          ignore: "*_state.dart, do_not_import_me.dart"

      - name: install dependencies
        run: dart pub get
      
      - name: build test
        run: dart pub run test


      - name: codecov test
        uses: codecov/codecov-action@v1
        with: 
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CODECOV_TOKEN }} 
          verbose: true 
      
