name: publish
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: publish
        run: |
          mkdir -p .pub-cache

          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_REFRESH_TOKEN }}",
            "tokenEndpoint":"${{ secrets.PUB_TOKEN_ENDPOINT }}",
            "scopes":["openid","https://www.googleapis.com/auth/userinfo.email"],
            "expiration": ${{ secrets.PUB_EXPIRATION }}
          }
          EOF

          pub publish -f

        